In [5]:
import numpy as np

In [6]:
import tensorflow as tf

## El Dataset

In [7]:
## Importar datos desde el dataset.
dataset = "proyecto_training_data.npy"
data = np.load(dataset)
print(data) 
print(type(data))
print(data.shape)

[[2.08500e+05 7.00000e+00 8.56000e+02 8.00000e+00 2.00300e+03 6.50000e+01]
 [1.81500e+05 6.00000e+00 1.26200e+03 6.00000e+00 1.97600e+03 8.00000e+01]
 [2.23500e+05 7.00000e+00 9.20000e+02 6.00000e+00 2.00100e+03 6.80000e+01]
 ...
 [2.66500e+05 7.00000e+00 1.18800e+03 9.00000e+00 1.94100e+03 6.60000e+01]
 [1.42125e+05 5.00000e+00 1.07800e+03 5.00000e+00 1.95000e+03 6.80000e+01]
 [1.47500e+05 5.00000e+00 1.25600e+03 6.00000e+00 1.96500e+03 7.50000e+01]]
<class 'numpy.ndarray'>
(1460, 6)


## 80% de los datos

In [8]:
## Slicing al dataset
trainingdata = data [:1168,]

print(trainingdata)
print("(Filas , Columnas) =", trainingdata.shape) 
print(type(trainingdata))

[[2.0850e+05 7.0000e+00 8.5600e+02 8.0000e+00 2.0030e+03 6.5000e+01]
 [1.8150e+05 6.0000e+00 1.2620e+03 6.0000e+00 1.9760e+03 8.0000e+01]
 [2.2350e+05 7.0000e+00 9.2000e+02 6.0000e+00 2.0010e+03 6.8000e+01]
 ...
 [2.3317e+05 7.0000e+00 1.5020e+03 7.0000e+00 2.0090e+03 7.9000e+01]
 [2.4535e+05 8.0000e+00 1.6940e+03 7.0000e+00 2.0080e+03 6.4000e+01]
 [1.7300e+05 6.0000e+00 9.5900e+02 7.0000e+00 2.0000e+03 5.8000e+01]]
(Filas , Columnas) = (1168, 6)
<class 'numpy.ndarray'>


## 20% de los datos

In [9]:
## Slicing al dataset 
dataprueba = data [1168:,]

print(dataprueba)
print("(Filas , Columnas) =", dataprueba.shape)
print(type(dataprueba))

[[2.35000e+05 6.00000e+00 1.23600e+03 7.00000e+00 1.93500e+03 1.20000e+02]
 [6.25000e+05 1.00000e+01 1.83100e+03 1.00000e+01 1.99500e+03 1.18000e+02]
 [1.71000e+05 6.00000e+00 1.11800e+03 6.00000e+00 1.97700e+03 7.60000e+01]
 ...
 [2.66500e+05 7.00000e+00 1.18800e+03 9.00000e+00 1.94100e+03 6.60000e+01]
 [1.42125e+05 5.00000e+00 1.07800e+03 5.00000e+00 1.95000e+03 6.80000e+01]
 [1.47500e+05 5.00000e+00 1.25600e+03 6.00000e+00 1.96500e+03 7.50000e+01]]
(Filas , Columnas) = (292, 6)
<class 'numpy.ndarray'>


# Extracción de los datos por Columnas

In [10]:
# Extracción por columnas del 80%

saleprice=trainingdata[:,0]
quality=trainingdata[:,1]

print(saleprice,"de tipo ", type(saleprice),"de rango ",saleprice.ndim, "de la forma ",saleprice.shape)
print(quality,"de tipo ", type(quality),"de rango ",quality.ndim, "de la forma ",quality.shape)

[208500. 181500. 223500. ... 233170. 245350. 173000.] de tipo  <class 'numpy.ndarray'> de rango  1 de la forma  (1168,)
[7. 6. 7. ... 7. 8. 6.] de tipo  <class 'numpy.ndarray'> de rango  1 de la forma  (1168,)


In [11]:
# Extracción por Columnas del 20%

saleprice20=dataprueba[:,0]
quality20=dataprueba[:,1]

## Las dos variables con mayor poder predictivo (Mayor correlación)
1. La variable Quality tiene un coeficiente de correlación de 0.79
2. La variable Square Feet tiene un coeficiente de correlación de 0.61

Dado que cada extracción de columna era un vector de 1168 filas, ahora lo convertiremos en una matriz de (1168,1)

In [12]:
saleprice=np.reshape(saleprice,(1168,1)) 
quality=np.reshape(quality,(1168,1)) 

print(saleprice,"de tipo ", type(saleprice),"de rango ",saleprice.ndim, "de la forma ",saleprice.shape)
print(quality,"de tipo ", type(quality),"de rango ",quality.ndim, "de la forma ",quality.shape)

[[208500.]
 [181500.]
 [223500.]
 ...
 [233170.]
 [245350.]
 [173000.]] de tipo  <class 'numpy.ndarray'> de rango  2 de la forma  (1168, 1)
[[7.]
 [6.]
 [7.]
 ...
 [7.]
 [8.]
 [6.]] de tipo  <class 'numpy.ndarray'> de rango  2 de la forma  (1168, 1)


Dado que cada extracción de columna era un vector de 292 filas, ahora lo convertiremos en una matriz de (292,1)

In [13]:
# Extracción por Columnas del 20%

saleprice20=np.reshape(saleprice20,(292,1)) 
quality20=np.reshape(quality20,(292,1)) 

print(saleprice20,"de tipo ", type(saleprice20),"de rango ",saleprice20.ndim, "de la forma ",saleprice20.shape)
print(quality20,"de tipo ", type(quality20),"de rango ",quality20.ndim, "de la forma ",quality20.shape)

[[235000.]
 [625000.]
 [171000.]
 [163000.]
 [171900.]
 [200500.]
 [239000.]
 [285000.]
 [119500.]
 [115000.]
 [154900.]
 [ 93000.]
 [250000.]
 [392500.]
 [745000.]
 [120000.]
 [186700.]
 [104900.]
 [ 95000.]
 [262000.]
 [195000.]
 [189000.]
 [168000.]
 [174000.]
 [125000.]
 [165000.]
 [158000.]
 [176000.]
 [219210.]
 [144000.]
 [178000.]
 [148000.]
 [116050.]
 [197900.]
 [117000.]
 [213000.]
 [153500.]
 [271900.]
 [107000.]
 [200000.]
 [140000.]
 [290000.]
 [189000.]
 [164000.]
 [113000.]
 [145000.]
 [134500.]
 [125000.]
 [112000.]
 [229456.]
 [ 80500.]
 [ 91500.]
 [115000.]
 [134000.]
 [143000.]
 [137900.]
 [184000.]
 [145000.]
 [214000.]
 [147000.]
 [367294.]
 [127000.]
 [190000.]
 [132500.]
 [101800.]
 [142000.]
 [130000.]
 [138887.]
 [175500.]
 [195000.]
 [142500.]
 [265900.]
 [224900.]
 [248328.]
 [170000.]
 [465000.]
 [230000.]
 [178000.]
 [186500.]
 [169900.]
 [129500.]
 [119000.]
 [244000.]
 [171750.]
 [130000.]
 [294000.]
 [165400.]
 [127500.]
 [301500.]
 [ 99900.]
 [190000.]

# Creación del Gráfo

In [14]:
grafoInicial = tf.Graph()
with grafoInicial.as_default():
    # cargando datos como constantes 
    trainingY = tf.constant(saleprice)
    trainingX = tf.constant(quality)
    pruebaY = tf.constant(saleprice20)
    pruebaX = tf.constant(quality20)
    
    #placeholder:
    ph_learningrate = tf.placeholder(dtype = tf.float64)    
  
    #Parametros beta1 y beta2:
    #Variables
    #Estimadores = tf.Variable(np.array([[0],[0]]))
    est0 = tf.Variable(0.0, name = "b0", dtype = tf.float64)
    est1 = tf.Variable(0.0, name = "b1", dtype = tf.float64)     
    
    #Parte de Entrenamiento
    #yhat = tf.matmul(trainingX, estimadores)
    #Hipotesis
    yhat = tf.add(tf.multiply(trainingX, est1), est0)
    
    #Costo
    error = (tf.reduce_mean(tf.pow(trainingY-yhat,2)))*.5
    
    ##para tensorboard
    recuento = tf.summary.scalar(name='Primer_Recuento_Escalar', tensor=error)
    
    # gradient descent un nodo mas del grafo
    optimizador = tf.train.GradientDescentOptimizer(ph_learningrate).minimize(error) 

Instructions for updating:
Colocations handled automatically by placer.


<img src="GRAFO.JPG">

## Primera Sesion

In [15]:
# epochs 
num_steps = 20

with tf.Session(graph = grafoInicial) as session:
    #Inicilizacion de variables
    tf.global_variables_initializer().run()
    print('Inicializado')
    writer = tf.summary.FileWriter('./graphs', session.graph)
    for step in range(num_steps): 
        # sesion que ejecuta los nodos y envia informacion con feed_dict al nodo del learning rate
        er, opti = session.run([error, optimizador],feed_dict={ph_learningrate:10.0})
        summary = session.run(recuento)
        writer.add_summary(summary, step)
        if (step % 2 == 0):
            print("Iteracion:", step, "Error:", er, "Beta1:", session.run(est1), "Beta0:", session.run(est0))

Inicializado
Iteracion: 0 Error: 19409722053.22175 Beta1: 11879476.738013685 Beta0: 1805902.7739726028
Iteracion: 2 Error: 4.5991659790119325e+20 Beta1: 1892177310679.6533 Beta0: 295456331982.5073
Iteracion: 4 Error: 1.1741538548192451e+31 Beta1: 3.02332463745082e+17 Beta0: 4.720808510516164e+16
Iteracion: 6 Error: 2.9975810420448657e+41 Beta1: 4.830674176285755e+22 Beta0: 7.542917317082002e+21
Iteracion: 8 Error: 7.652738239325503e+51 Beta1: 7.718460898434383e+27 Beta0: 1.2052088434742129e+27
Iteracion: 10 Error: 1.9537220758403224e+62 Beta1: 1.2332572321502991e+33 Beta0: 1.925685110055494e+32
Iteracion: 12 Error: 4.987796302781102e+72 Beta1: 1.970500881800828e+38 Beta0: 3.076863535451501e+37
Iteracion: 14 Error: 1.2733700594203426e+83 Beta1: 3.148470265532254e+43 Beta0: 4.9162187350133154e+42
Iteracion: 16 Error: 3.250877160568992e+93 Beta1: 5.030632112116291e+48 Beta0: 7.855144166135146e+47
Iteracion: 18 Error: 8.299395949296999e+103 Beta1: 8.037954089802256e+53 Beta0: 1.25509651210

## Segunda Sesion

In [16]:
# epochs 
num_steps = 20

with tf.Session(graph = grafoInicial) as session2:
    #Inicilizacion de variables
    tf.global_variables_initializer().run()
    print('Inicializado')
    writer = tf.summary.FileWriter('./graphs2', session2.graph)
    for step in range(num_steps): 
        # sesion que ejecuta los nodos y envia informacion con feed_dict al nodo del learning rate
        er, opti = session2.run([error, optimizador],feed_dict={ph_learningrate:1})
        summary = session2.run(recuento)
        writer.add_summary(summary, step)
        if (step % 2 == 0):
            print("Iteracion:", step, "Error:", er, "Beta1:", session2.run(est1), "Beta0:", session2.run(est0))

Inicializado
Iteracion: 0 Error: 19409722053.22175 Beta1: 1187947.6738013686 Beta0: 180590.27739726027
Iteracion: 2 Error: 4.1987369532118696e+16 Beta1: 1767255346.729938 Beta0: 275936297.83559537
Iteracion: 4 Error: 9.785976057427764e+22 Beta1: 2697952202783.967 Beta0: 421275138232.01025
Iteracion: 6 Error: 2.280812814548885e+29 Beta1: 4118859651756539.0 Beta0: 643144552057379.6
Iteracion: 8 Error: 5.31587964704039e+35 Beta1: 6.288104370696646e+18 Beta0: 9.818640135612266e+17
Iteracion: 10 Error: 1.2389695568861071e+42 Beta1: 9.59980672326122e+21 Beta0: 1.4989739678365697e+21
Iteracion: 12 Error: 2.8876604904800966e+48 Beta1: 1.4655655137251198e+25 Beta0: 2.2884258158133876e+24
Iteracion: 14 Error: 6.730256657182867e+54 Beta1: 2.237422415824094e+28 Beta0: 3.4936515422208277e+27
Iteracion: 16 Error: 1.5686177381615557e+61 Beta1: 3.4157866161219335e+31 Beta0: 5.33362323310606e+30
Iteracion: 18 Error: 3.655969948559207e+67 Beta1: 5.214749849808942e+34 Beta0: 8.14263713737335e+33


## Tercera Sesion

In [17]:
# epochs 
num_steps = 20

with tf.Session(graph = grafoInicial) as session3:
    #Inicilizacion de variables
    tf.global_variables_initializer().run()
    print('Inicializado')
    writer = tf.summary.FileWriter('./graphs3', session3.graph)
    for step in range(num_steps): 
        # sesion que ejecuta los nodos y envia informacion con feed_dict al nodo del learning rate
        er, opti = session3.run([error, optimizador],feed_dict={ph_learningrate:0.1})
        summary = session3.run(recuento)
        writer.add_summary(summary, step)
        if (step % 2 == 0):
            print("Iteracion:", step, "Error:", er, "Beta1:", session3.run(est1), "Beta0:", session3.run(est0))

Inicializado
Iteracion: 0 Error: 19409722053.22175 Beta1: 118794.76738013687 Beta0: 18059.02773972603
Iteracion: 2 Error: 1474761375440.7397 Beta1: 835574.1204399086 Beta0: 129007.73751476406
Iteracion: 4 Error: 120502547628807.03 Beta1: 7316617.37917742 Beta0: 1140033.9272875148
Iteracion: 6 Error: 9855311023202318.0 Beta1: 65927149.82447075 Beta0: 10290894.279479643
Iteracion: 8 Error: 8.060264865517955e+17 Beta1: 595973959.8531418 Beta0: 93054777.7484751
Iteracion: 10 Error: 6.592169281403146e+19 Beta1: 5389483976.492045 Beta0: 841542527.2905977
Iteracion: 12 Error: 5.391472443170872e+21 Beta1: 48739887758.78403 Beta0: 7610545250.360823
Iteracion: 14 Error: 4.4094703678292546e+23 Beta1: 440781950043.9867 Beta0: 68826448213.13431
Iteracion: 16 Error: 3.606330020177906e+25 Beta1: 3986238637613.265 Beta0: 622436267995.6798
Iteracion: 18 Error: 2.949473548869538e+27 Beta1: 36049795934814.13 Beta0: 5629040992611.314


## Cuarta Sesion

In [18]:
# epochs 
num_steps = 20

with tf.Session(graph = grafoInicial) as session4:
    #Inicilizacion de variables
    tf.global_variables_initializer().run()
    print('Inicializado')
    writer = tf.summary.FileWriter('./graphs4', session4.graph)
    for step in range(num_steps): 
        # sesion que ejecuta los nodos y envia informacion con feed_dict al nodo del learning rate
        er, opti = session4.run([error, optimizador],feed_dict={ph_learningrate:0.01})
        summary = session4.run(recuento)
        writer.add_summary(summary, step)
        if (step % 2 == 0):
            print("Iteracion:", step, "Error:", er, "Beta1:", session4.run(est1), "Beta0:", session4.run(est0))

Inicializado
Iteracion: 0 Error: 19409722053.22175 Beta1: 11879.476738013685 Beta0: 1805.9027739726027
Iteracion: 2 Error: 3717770447.2485785 Beta1: 23272.603178250207 Beta0: 3486.900249135218
Iteracion: 4 Error: 1693499585.3201845 Beta1: 27373.779446738263 Beta0: 4029.379713620872
Iteracion: 6 Error: 1432013147.1072404 Beta1: 28856.186135910168 Beta0: 4163.040776370932
Iteracion: 8 Error: 1397881894.3230965 Beta1: 29398.1041799059 Beta0: 4149.940649695315
Iteracion: 10 Error: 1393074454.206566 Beta1: 29602.255186377413 Beta0: 4084.191974002789
Iteracion: 12 Error: 1392049808.282319 Beta1: 29685.094778536117 Beta0: 3999.593398886302
Iteracion: 14 Error: 1391513812.4658086 Beta1: 29724.358746045444 Beta0: 3908.2829900844226
Iteracion: 16 Error: 1391041604.3933318 Beta1: 29747.964377854983 Beta0: 3814.6198405871837
Iteracion: 18 Error: 1390578386.1651592 Beta1: 29765.937627907548 Beta0: 3720.169378324098


## Quinta Sesion

In [19]:
# epochs 
num_steps = 20

with tf.Session(graph = grafoInicial) as session5:
    #Inicilizacion de variables
    tf.global_variables_initializer().run()
    print('Inicializado')
    writer = tf.summary.FileWriter('./graphs5', session5.graph)
    for step in range(num_steps): 
        # sesion que ejecuta los nodos y envia informacion con feed_dict al nodo del learning rate
        er, opti = session5.run([error, optimizador],feed_dict={ph_learningrate:0.001})
        summary = session5.run(recuento)
        writer.add_summary(summary, step)
        if (step % 2 == 0):
            print("Iteracion:", step, "Error:", er, "Beta1:", session5.run(est1), "Beta0:", session5.run(est0))

Inicializado
Iteracion: 0 Error: 19409722053.22175 Beta1: 1187.9476738013686 Beta0: 180.59027739726028
Iteracion: 2 Error: 16691037688.98972 Beta1: 3423.0270258274136 Beta0: 519.7836368482164
Iteracion: 4 Error: 14382623015.887161 Beta1: 5482.682230497807 Beta0: 831.5860993870335
Iteracion: 6 Error: 12422564219.848372 Beta1: 7380.690953254501 Beta0: 1118.1489959296696
Iteracion: 8 Error: 10758290902.950512 Beta1: 9129.748772377112 Beta0: 1381.4546935229175
Iteracion: 10 Error: 9345166068.111794 Beta1: 10741.554165269808 Beta0: 1623.3298656357094
Iteracion: 12 Error: 8145288889.255076 Beta1: 12226.886819991123 Beta0: 1845.4577202120292
Iteracion: 14 Error: 7126478155.473641 Beta1: 13595.679796256918 Beta0: 2049.3892673420282
Iteracion: 16 Error: 6261409123.678336 Beta1: 14857.086018974107 Beta0: 2236.5537019789867
Iteracion: 18 Error: 5526880628.846098 Beta1: 16019.539549423798 Beta0: 2408.267971205734


## Sexta Sesion

In [20]:
# epochs 
num_steps = 20

with tf.Session(graph = grafoInicial) as session6:
    #Inicilizacion de variables
    tf.global_variables_initializer().run()
    print('Inicializado')
    writer = tf.summary.FileWriter('./graphs6', session6.graph)
    for step in range(num_steps): 
        # sesion que ejecuta los nodos y envia informacion con feed_dict al nodo del learning rate
        er, opti = session6.run([error, optimizador],feed_dict={ph_learningrate:0.0001})
        summary = session6.run(recuento)
        writer.add_summary(summary, step)
        if (step % 2 == 0):
            print("Iteracion:", step, "Error:", er, "Beta1:", session6.run(est1), "Beta0:", session6.run(est0))

Inicializado
Iteracion: 0 Error: 19409722053.22175 Beta1: 118.79476738013686 Beta0: 18.059027739726027
Iteracion: 2 Error: 19122686627.97568 Beta1: 354.95898445942515 Beta0: 53.9545321511267
Iteracion: 4 Error: 18840224439.06416 Beta1: 589.2354492233663 Beta0: 89.55528037486923
Iteracion: 6 Error: 18562262621.50268 Beta1: 821.6392607438453 Beta0: 124.86363007455056
Iteracion: 8 Error: 18288729471.258484 Beta1: 1052.185397323649 Beta0: 159.88192005612413
Iteracion: 10 Error: 18019554426.753 Beta1: 1280.8887174624338 Beta0: 194.61247041873187
Iteracion: 12 Error: 17754668050.65932 Beta1: 1507.7639608149611 Beta0: 229.0575827043294
Iteracion: 14 Error: 17494002011.989506 Beta1: 1732.8257491416753 Beta0: 263.2195400461148
Iteracion: 16 Error: 17237489068.46755 Beta1: 1956.0885872516722 Beta0: 297.10060731577
Iteracion: 18 Error: 16985063049.182821 Beta1: 2177.5668639381292 Beta0: 330.7030312695244
